# Input file for NN Extender
# input.structure -- structure of your neural network BEFORE extending
# output.structure -- structure of your neural network AFTER extending

[input]
file_name = "model-iter-101.bson"
structure = [8, 30, 30, 30, 1]
activations = ["identity", "relu", "relu", "identity"]
bias = false
f64 = true

[output]
file_name ="output_model.bson"
structure = [8, 10, 8, 1]
activations = ["identity", "relu", "identity"]
bias = false
f64 = true

